name: microsocks-ubuntu-20.04
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update && sudo apt install -y build-essential tree
    - run: make
    - run: tree -a .
    - uses: actions/upload-artifact@v2
      with:
        name: microsocks-ubuntu-20.04_${{ github.sha }}
        path: ./microsocks
